server:
  port: 9002
spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  cloud:
    gateway:
      routes: # 路由可以有多个
      # 我们⾃定义的路由 ID，保持唯⼀
        - id: service-user-router  
          # gateway⽹关从服务注册中⼼获取实例信息然后负载后路由
          # ⽬标服务地址 用户微服务（部署多实例） 动态路由：uri配置的应该是⼀个服务名称，⽽不应该是⼀个具体的服务实例的地址
          uri: lb://lagou-service-user  
           # 断⾔：路由条件，Predicate 接受⼀个输⼊参数，返回⼀个布尔值结果。该接⼝包含多种默 认⽅法来将Predicate 组合成其他复杂的逻辑（⽐如：与，或，⾮）。
          predicates: 
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        # 验证码微服务    
        - id: service-code-router
          uri: lb://lagou-service-code
          predicates:
            - Path=/api/code/**
          filters:
            - StripPrefix=1
        # 邮件微服务
        - id: service-email-router
          uri: lb://lagou-service-email 
          predicates:
            - Path=/api/email/**
          filters:
            - StripPrefix=1
    sentinel:
      transport:
        # sentinel dashboard/console 地址
        dashboard: 127.0.0.1:8080 
        port: 8719
dubbo:
  registry:
    # 挂载到 Spring Cloud 注册中⼼
    address: spring-cloud://localhost
  cloud:
    # 订阅服务提供⽅的应⽤列表，订阅多个服务提供者使⽤ "," 连接
    subscribed-services: lagou-service-user
  consumer:
    check: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # 暴露健康接⼝的细节
  endpoint:
    health:
      show-details: always
# ip防暴刷配置
limit:
  minute: 1
  count: 10