server:
  port: 8085
spring:
  # 邮箱配置
  mail:
    host: smtp.qq.com
    username: 517309804@qq.com
    password: awznvjqobwkkbjfi
    default-encoding: UTF-8
dubbo:
  scan:
    base-packages: com.lagou.service
  protocol:
    name: dubbo
    port: 20880
  registry:
    # 挂载到 Spring Cloud 的注册中⼼
    address: spring-cloud://localhost
