server:
  port: 8082
spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/lagou?serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
dubbo:
  scan:
    base-packages: com.lagou.impl
  protocol:
    # dubbo 协议
    name: dubbo
    port: -1
  registry:
    # 挂载到 Spring Cloud 的注册中⼼
    address: spring-cloud://localhost
  cloud:
    # 订阅服务提供⽅的应⽤列表，订阅多个服务提供者使⽤ "," 连接
    subscribed-services: lagou-service-code
